import { useState } from 'react'
import {
  Sparkles, MapPin, Calendar, DollarSign, Users,
  Copy, Download, ChevronDown, ChevronUp, Loader2,
  Clock, Utensils, Hotel, Camera, AlertCircle
} from 'lucide-react'
import toast from 'react-hot-toast'
import { aiAPI } from '../services/api'
import PageWrapper from '../components/Layout/PageWrapper'
import clsx from 'clsx'

const TRIP_TYPES = ['Adventure', 'Cultural', 'Beach', 'Business', 'Family', 'Honeymoon', 'Budget']

const CURRENCY_SYMBOLS = {
  INR: '₹', USD: '$', EUR: '€', GBP: '£', JPY: '¥', AED: 'د.إ', SGD: 'S$',
}

const typeColors = {
  Travel:   'bg-blue-50 text-blue-600 border-blue-200',
  Food:     'bg-amber-50 text-amber-600 border-amber-200',
  Hotel:    'bg-purple-50 text-purple-600 border-purple-200',
  Activity: 'bg-emerald-50 text-emerald-600 border-emerald-200',
  Other:    'bg-slate-50 text-slate-500 border-slate-200',
}

export default function AIPlanner() {
  const [form, setForm]       = useState({ origin: '', destination: '', days: '5', budget: '', travelers: '2', type: 'Cultural', currency: 'INR', transport: 'Flight' })
  const [loading, setLoading] = useState(false)
  const [itinerary, setItinerary] = useState(null)
  const [expanded, setExpanded]   = useState([])
  const [error, setError]     = useState(null)

  const set = (k, v) => setForm(p => ({ ...p, [k]: v }))
  const toggleDay = (i) => setExpanded(p => p.includes(i) ? p.filter(x => x !== i) : [...p, i])

  const generate = async () => {
    if (!form.destination) { toast.error('Enter a destination'); return }
    if (!form.budget)       { toast.error('Enter your budget'); return }
    setLoading(true)
    setError(null)
    setItinerary(null)
    try {
      const res = await aiAPI.generateItinerary({
        origin: form.origin,
        destination: form.destination,
        days:       parseInt(form.days),
        budget:     parseFloat(form.budget),
        currency:   form.currency,
        travelers:  parseInt(form.travelers),
        tripType:   form.type,
        preferredTransport: form.transport,
      })
      const data = res.data.data
      setItinerary(data)
      setExpanded(data.days.map((_, i) => i))
      toast.success('Itinerary generated by Gemini AI ✈️')
    } catch (err) {
      const msg = err?.message || 'Failed to generate itinerary. Check your Gemini API key.'
      setError(msg)
      toast.error(msg)
    } finally {
      setLoading(false)
    }
  }

  return (
    <PageWrapper icon={Sparkles} title="AI Trip Planner" subtitle="Powered by Gemini AI" iconColor="text-blue-600" iconBg="bg-blue-100">
      {/* Input card */}
      <div className="glass-card rounded-[18px] p-6 space-y-5 shadow-sm">
        <h2 className="font-bold text-sm text-slate-500 uppercase tracking-wider">Plan Your Trip</h2>
        <div className="grid md:grid-cols-2 gap-4">
          <div>
            <label className="text-xs font-semibold text-slate-500 mb-1.5 block">From</label>
            <div className="relative">
              <MapPin size={15} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
              <input className="input-field input-with-icon" placeholder="e.g. New York, USA" value={form.origin} onChange={e => set('origin', e.target.value)} />
            </div>
          </div>
          <div>
            <label className="text-xs font-semibold text-slate-500 mb-1.5 block">To *</label>
            <div className="relative">
              <MapPin size={15} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
              <input className="input-field input-with-icon" placeholder="e.g. Tokyo, Japan" value={form.destination} onChange={e => set('destination', e.target.value)} />
            </div>
          </div>
          <div>
            <label className="text-xs font-semibold text-slate-500 mb-1.5 block">Budget *</label>
            <div className="flex flex-col sm:flex-row gap-2">
              <select className="input-field w-full max-w-[7rem]" value={form.currency} onChange={e => set('currency', e.target.value)}>
                {['INR','USD','EUR','GBP','JPY','AED','SGD'].map(c => <option key={c}>{c}</option>)}
              </select>
              <div className="relative flex-1 min-w-0">
                <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none text-sm">{CURRENCY_SYMBOLS[form.currency] || '$'}</span>
                <input className="input-field input-with-icon w-full" placeholder="e.g. 80000" value={form.budget} onChange={e => set('budget', e.target.value)} />
              </div>
            </div>
          </div>
          <div>
            <label className="text-xs font-semibold text-slate-500 mb-1.5 block">Duration (days)</label>
            <div className="relative">
              <Calendar size={15} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
              <input type="number" min="1" max="30" className="input-field input-with-icon" value={form.days} onChange={e => set('days', e.target.value)} />
            </div>
          </div>
          <div>
            <label className="text-xs font-semibold text-slate-500 mb-1.5 block">Travellers</label>
            <div className="relative">
              <Users size={15} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
              <input type="number" min="1" max="20" className="input-field input-with-icon" value={form.travelers} onChange={e => set('travelers', e.target.value)} />
            </div>
          </div>
        </div>

        <div>
          <label className="text-xs font-semibold text-slate-500 mb-2 block">Trip Type</label>
          <div className="flex flex-wrap gap-2">
            {TRIP_TYPES.map(t => (
              <button key={t} onClick={() => set('type', t)}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition-all duration-200 ${form.type === t ? 'bg-blue-50 border-blue-200 text-blue-600 shadow-sm' : 'bg-slate-50 border-slate-200 text-slate-600 hover:bg-slate-100'}`}>
                {t}
              </button>
            ))}
          </div>
        </div>

        <div>
          <label className="text-xs font-semibold text-slate-500 mb-2 block">Preferred Transport</label>
          <div className="flex flex-wrap gap-2">
            {['Flight', 'Train', 'Bus'].map(t => (
              <button key={t} onClick={() => set('transport', t)}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition-all duration-200 ${form.transport === t ? 'bg-orange-50 border-orange-200 text-orange-600 shadow-sm' : 'bg-slate-50 border-slate-200 text-slate-600 hover:bg-slate-100'}`}>
                {t}
              </button>
            ))}
          </div>
        </div>

        {error && (
          <div className="flex items-start gap-2 p-3 rounded-xl bg-red-50 border border-red-200">
            <AlertCircle size={15} className="text-red-500 flex-shrink-0 mt-0.5" />
            <p className="text-red-600 text-xs font-medium">{error}</p>
          </div>
        )}

        <button onClick={generate} disabled={loading} className="btn-primary w-full py-3.5 disabled:opacity-60 disabled:cursor-not-allowed text-sm">
          {loading ? <><Loader2 size={16} className="animate-spin" /> Gemini is planning your trip…</> : <><Sparkles size={16} /> Generate Itinerary with Gemini AI</>}
        </button>
      </div>

      {/* Skeleton */}
      {loading && (
        <div className="space-y-3">
          {[1,2,3].map(i => (
            <div key={i} className="glass-card rounded-[18px] p-5 space-y-3 animate-pulse">
              <div className="h-4 bg-slate-200 rounded w-1/3" />
              <div className="h-3 bg-slate-100 rounded w-2/3" />
              <div className="h-3 bg-slate-100 rounded w-1/2" />
            </div>
          ))}
        </div>
      )}

      {/* Result */}
      {itinerary && !loading && (
        <div className="space-y-4">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div>
              <h2 className="font-extrabold text-2xl text-slate-900 tracking-tight">{itinerary.destination}</h2>
              <p className="text-slate-500 text-sm mt-1">{itinerary.summary}</p>
            </div>
            <div className="flex gap-2">
              <button onClick={() => { navigator.clipboard?.writeText(JSON.stringify(itinerary, null, 2)); toast.success('Copied') }} className="btn-outline text-xs px-4 py-2.5 gap-1.5 shadow-sm">
                <Copy size={13}/> Copy JSON
              </button>
            </div>
          </div>

          {itinerary.days?.map((day, i) => (
            <div key={i} className="glass-card rounded-[18px] overflow-hidden shadow-sm">
              <button onClick={() => toggleDay(i)} className="w-full flex items-center justify-between px-5 py-4 hover:bg-slate-50 transition-colors">
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl bg-blue-50 border border-blue-100 flex items-center justify-center text-blue-600 text-sm font-extrabold">{day.day}</div>
                  <div className="text-left py-1">
                    <p className="font-bold text-sm text-slate-800">Day {day.day}</p>
                    <p className="text-slate-500 text-xs mt-0.5">{day.title}</p>
                  </div>
                </div>
                {expanded.includes(i) ? <ChevronUp size={16} className="text-slate-400" /> : <ChevronDown size={16} className="text-slate-400" />}
              </button>

              {expanded.includes(i) && (
                <div className="border-t border-slate-100 divide-y divide-slate-100 bg-slate-50/50">
                  {day.activities?.map((act, j) => (
                    <div key={j} className="flex items-start gap-4 px-5 py-5 hover:bg-slate-50 transition-colors">
                      <div className="flex flex-col items-center gap-1.5 flex-shrink-0 w-14">
                        <span className="text-2xl drop-shadow-sm">{act.icon}</span>
                        <span className="text-slate-500 text-[10px] font-semibold">{act.time}</span>
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2.5 mb-1.5 flex-wrap">
                          <p className="font-bold text-sm text-slate-800">{act.title}</p>
                          <span className={clsx('text-[10px] font-bold px-2 py-0.5 rounded-full border', typeColors[act.type] || typeColors.Other)}>{act.type}</span>
                        </div>
                        <p className="text-slate-600 text-xs leading-relaxed">{act.desc}</p>
                      </div>
                      <span className={clsx('flex-shrink-0 text-xs font-bold px-2.5 py-1 rounded-md', act.cost === 'Free' ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-600')}>{act.cost}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}

          {/* Cost breakdown */}
          {itinerary.costBreakdown && (
            <div className="bg-blue-50 border border-blue-100 rounded-2xl p-6">
              <h3 className="font-extrabold text-sm mb-4 text-blue-800">Estimated Cost Breakdown</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {[
                  { icon: <Hotel size={14}/>,    label: 'Accommodation', val: itinerary.costBreakdown.accommodation },
                  { icon: <Utensils size={14}/>, label: 'Food & Dining',  val: itinerary.costBreakdown.food },
                  { icon: <Camera size={14}/>,   label: 'Activities',    val: itinerary.costBreakdown.activities },
                  { icon: <Clock size={14}/>,    label: 'Transport',     val: itinerary.costBreakdown.transport },
                ].map((row, i) => (
                  <div key={i} className="bg-white rounded-xl p-3.5 shadow-sm border border-blue-100/50">
                    <div className="flex items-center gap-2 mb-2 text-slate-500">{row.icon}<span className="text-xs font-semibold">{row.label}</span></div>
                    <p className="font-extrabold text-sm text-slate-800">{form.currency} {row.val?.toLocaleString?.() ?? row.val}</p>
                  </div>
                ))}
              </div>
              <div className="border-t border-blue-200 mt-5 pt-4 flex items-center justify-between">
                <span className="text-blue-800 text-sm font-bold">Total Estimated</span>
                <span className="text-blue-600 font-extrabold text-xl">{form.currency} {itinerary.costBreakdown.total?.toLocaleString?.()}</span>
              </div>
            </div>
          )}

          {/* Tips */}
          {itinerary.tips?.length > 0 && (
            <div className="glass-card rounded-[18px] p-6 shadow-sm">
              <h3 className="font-extrabold text-sm mb-3 text-slate-800">💡 Travel Tips</h3>
              <ul className="space-y-2.5">
                {itinerary.tips.map((tip, i) => (
                  <li key={i} className="flex items-start gap-3 text-sm text-slate-600 font-medium">
                    <span className="text-blue-500 font-bold mt-0.5">›</span> {tip}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </PageWrapper>
  )
}